<a href="https://colab.research.google.com/github/Batman511/Numerical_methods_7sem/blob/main/1)%20%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%20%D0%93%D0%B0%D1%83%D1%81%D1%81%D0%B0%20%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%A1%D0%9B%D0%90%D0%A3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# СЛАУ

Самостоятельный ввод

In [ ]:
# матрица коэффициентов А и ответов b
A = np.array([[3.8, 6.7, -1.2], 
              [6.4, 1.3, -2.7], 
              [2.4, -4.5, 3.5]])

b = np.array([5.2,3.8, -0.6])

# для приведения к диагональному виду
matrix=np.column_stack((A,b))
matrix

array([[ 3.8,  6.7, -1.2,  5.2],
       [ 6.4,  1.3, -2.7,  3.8],
       [ 2.4, -4.5,  3.5, -0.6]])

Автоматическое заполнение

In [ ]:
row = 10
matrix = np.round(np.random.rand(row, row+1), 2)*10
print(matrix)

[[8.4 0.7 8.4 6.5 0.8 3.1 9.  3.7 3.5 6.5 5.3]
 [0.2 0.7 3.  8.9 4.8 4.3 2.3 9.5 8.6 1.3 0.7]
 [8.4 7.8 8.  3.5 7.8 6.8 0.4 5.6 1.  7.9 3.1]
 [8.4 2.6 0.9 2.1 2.3 9.2 9.7 6.4 2.4 7.6 2.2]
 [8.4 8.8 3.1 3.6 0.6 0.4 3.9 2.1 1.4 4.7 0.2]
 [3.  1.1 0.2 8.1 9.7 6.5 9.1 4.8 9.9 9.9 7.4]
 [2.2 6.  4.5 8.7 7.6 9.9 6.3 5.4 0.5 6.9 5.1]
 [0.2 3.2 6.6 8.3 8.2 4.3 4.6 9.2 8.2 1.  7.5]
 [7.5 3.2 4.7 8.8 0.6 0.1 5.3 8.3 3.4 2.3 6.9]
 [9.4 0.9 7.  3.3 0.8 1.4 2.1 8.1 5.6 6.2 2.4]]


# Метод Гаусса решения СЛАУ

Приведение к диагональному виду

In [ ]:
def Triangle_matrix(A):
    for num in range(A.shape[0]):
        row = A[num]
        divider = row[num] # диаг. элемент
        row /= divider
        
        for new_row in A[num+1:]:
            new_row -= new_row[num]*row


    for num in range(len(A)-1,0,-1):
        row = A[num]
        for new_row in A[:num]:
            new_row[-1] -= new_row[num]*row[-1]
            new_row[num] = 0
    return A

matrix_2 = matrix.copy()
print('result matrix:\n',Triangle_matrix(matrix_2))
ans_1 = Triangle_matrix(matrix_2)[:,-1]  
print('\nanswers:\n',ans_1)  

result matrix:
 [[ 1.          0.          0.          0.53344344]
 [-0.          1.          0.          0.49024295]
 [ 0.          0.          1.          0.09309401]]

answers:
 [0.53344344 0.49024295 0.09309401]


Невязка для ручного ввода

In [ ]:
# r = b - Ax
def discrep(A,b,ans):
  return b - np.matmul(A, ans.T)

print('r:\n',discrep(A,b,ans_1))

r:
 [0.00000000e+00 0.00000000e+00 2.22044605e-16]


Невязка для автоматического ввода

In [ ]:
def discrep_auto(A,ans):
  return A[:,-1] - np.matmul(A[:,:-1], ans.T)

print('r:\n',discrep_auto(matrix,ans_1))

r:
 [0.00000000e+00 0.00000000e+00 2.22044605e-16]


In [ ]:
# # пример проблемной марицы
# withZero = np.array([[1,0,0,7],
#                      [0,0,1,4],
#                      [0,1,3,2]], dtype=float)


# Метод Гаусса с выбором главного элемента

In [ ]:
def Triangle_matrix_with_main_element(A):
    for num in range(len(A)):
        ele = num + np.argmax(abs(A[num:, num]))
        if ele != num:
            A[num], A[ele] = A[ele], np.copy(A[num])
        row = A[num]
        divider = row[num]
        row /= divider

        for new_row in A[num+1:]:
            new_row -= new_row[num]*row

    for num in range(len(A)-1,0,-1):
        row = A[num]
        for new_row in A[:num]:
            new_row[-1] -= new_row[num]*row[-1]
            new_row[num] = 0
    return A


matrix_2 = matrix.copy()
print('result matrix:\n',Triangle_matrix_with_main_element(matrix_2))
ans_2 = Triangle_matrix_with_main_element(matrix_2)[:,-1]  
print('\nanswers:\n',ans_2)   

result matrix:
 [[1.         0.         0.         0.53344344]
 [0.         1.         0.         0.49024295]
 [0.         0.         1.         0.09309401]]

answers:
 [0.53344344 0.49024295 0.09309401]


# Сравнение двух методов

In [ ]:
row = 200
matrix = np.round(np.random.rand(row, row+1), 2)*10
b = matrix[:,-1] 
A = matrix[:,:-1]

matrix_2 = matrix.copy()
ans_1 = Triangle_matrix(matrix_2)[:,-1]

matrix_2 = matrix.copy()
ans_2 = Triangle_matrix_with_main_element(matrix_2)[:,-1]  

In [ ]:
answer = np.linalg.solve(A, b)
print("Макс ошибка для метода Гаусса:                        ",max(abs(ans_1 - answer)),"\nМакс ошибка для метода Гаусса с выбором гл. элемента: ",max(abs(ans_2 - answer)))

print('\nМакс невязка для метода Гаусса:                        \n',max(abs(discrep_auto(matrix,ans_1))))
print('Макс невязка для метода Гаусса с выбором гл. элемента:\n',max(abs(discrep_auto(matrix,ans_2))))

Макс ошибка для метода Гаусса:                         4.0592862404764674e-11 
Макс ошибка для метода Гаусса с выбором гл. элемента:  1.652011860642233e-13

Макс невязка для метода Гаусса:                        
 1.263114057792336e-10
Макс невязка для метода Гаусса с выбором гл. элемента:
 6.110667527536862e-13
